/* 単語データ（現在：各レアリティ20語 × 5レベル = 100語）
   ── IDのルール ──────────────────────────────────────────
   ・id は「通し番号」。レアリティや並び順とは無関係で、一度使った番号は二度と使わない（永久欠番）。
   ・新しい単語は、必ず「次のID」を使う（下の NEXT_ID）。どのレアリティの単語でも、番号は続きから。
   ・単語を消しても、番号は詰めない（セーブデータの owned / mastery は id で保存されている）。
   ・レアリティを変えても、id は変えない。
   ・図鑑の並びは、この配列の並び。同じレアリティの単語は、まとめて並べておく（途中に追加してよい）。
   ・ex は、カードゲーム風の一文（そのまま例文として使う）。tr はその日本語訳。
   ・カード画像は assets/cards/単語(en).webp（id ではなく en で対応）。
   次に使うID：101 */
const WORDS=[{"id": 1, "en": "apple", "ja": "りんご", "pronunciation": "ˈæpəl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍎", "ex": "The knight eats a red apple.", "tr": "騎士は赤いりんごを食べる。"},
{"id": 2, "en": "book", "ja": "本", "pronunciation": "bʊk", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "📖", "ex": "She reads a big book.", "tr": "少女は大きな本を読んでいる。"},
{"id": 3, "en": "cat", "ja": "猫", "pronunciation": "kæt", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐈", "ex": "The black cat sleeps on a stone wall.", "tr": "黒猫が石壁の上で眠っている。"},
{"id": 4, "en": "dog", "ja": "犬", "pronunciation": "dɔːɡ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐕", "ex": "The brave dog guards the gate.", "tr": "勇敢な犬が門を守っている。"},
{"id": 5, "en": "house", "ja": "家", "pronunciation": "haʊs", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏠", "ex": "A small house stands by the lake.", "tr": "湖のそばに小さな家が立っている。"},
{"id": 6, "en": "school", "ja": "学校", "pronunciation": "skuːl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏫", "ex": "The children walk to the old school.", "tr": "子どもたちは古い学校へ歩いていく。"},
{"id": 7, "en": "water", "ja": "水", "pronunciation": "ˈwɔːtər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "💧", "ex": "The traveler drinks cold water from a spring.", "tr": "旅人が泉の冷たい水を飲む。"},
{"id": 8, "en": "food", "ja": "食べ物", "pronunciation": "fuːd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍲", "ex": "The cook makes hot food for the guests.", "tr": "料理人が客のために温かい食べ物を作る。"},
{"id": 9, "en": "friend", "ja": "友達", "pronunciation": "frend", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🤝", "ex": "The hero helps his best friend.", "tr": "勇者は親友を助ける。"},
{"id": 10, "en": "family", "ja": "家族", "pronunciation": "ˈfæməli", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👨‍👩‍👧", "ex": "The family sits around a warm fire.", "tr": "家族が暖かい火のまわりに座っている。"},
{"id": 11, "en": "sun", "ja": "太陽", "pronunciation": "sʌn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "☀️", "ex": "The sun rises over the castle.", "tr": "太陽が城の上に昇る。"},
{"id": 12, "en": "moon", "ja": "月", "pronunciation": "muːn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌙", "ex": "The moon shines on the lake.", "tr": "月が湖を照らしている。"},
{"id": 13, "en": "car", "ja": "車", "pronunciation": "kɑːr", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🚗", "ex": "The old car stops at the bridge.", "tr": "古い車が橋の前で止まる。"},
{"id": 14, "en": "go", "ja": "行く", "pronunciation": "ɡoʊ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🚶", "ex": "We go to the forest at dawn.", "tr": "私たちは夜明けに森へ行く。"},
{"id": 15, "en": "come", "ja": "来る", "pronunciation": "kʌm", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "👋", "ex": "Come here and see the stars.", "tr": "ここに来て、星を見て。"},
{"id": 16, "en": "eat", "ja": "食べる", "pronunciation": "iːt", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🍽️", "ex": "The giant likes to eat bread.", "tr": "巨人はパンを食べるのが好きだ。"},
{"id": 17, "en": "drink", "ja": "飲む", "pronunciation": "drɪŋk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🥤", "ex": "Drink this tea and rest.", "tr": "このお茶を飲んで休みなさい。"},
{"id": 18, "en": "sleep", "ja": "眠る", "pronunciation": "sliːp", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "😴", "ex": "The baby dragon sleeps all day.", "tr": "子どものドラゴンは一日中眠っている。"},
{"id": 19, "en": "happy", "ja": "幸せな", "pronunciation": "ˈhæpi", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "😊", "ex": "The princess is happy today.", "tr": "姫は今日、幸せそうだ。"},
{"id": 20, "en": "big", "ja": "大きい", "pronunciation": "bɪɡ", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🐘", "ex": "A big bird flies above the town.", "tr": "大きな鳥が町の上を飛んでいる。"},
{"id": 21, "en": "important", "ja": "重要な", "pronunciation": "ɪmˈpɔːrtənt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⭐", "ex": "This old map is very important.", "tr": "この古い地図はとても大切だ。"},
{"id": 22, "en": "different", "ja": "違う", "pronunciation": "ˈdɪfrənt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔀", "ex": "Each door leads to a different world.", "tr": "どの扉も、違う世界につながっている。"},
{"id": 23, "en": "usually", "ja": "たいてい", "pronunciation": "ˈjuːʒuəli", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🕒", "ex": "The wizard usually wakes up before dawn.", "tr": "魔法使いはたいてい夜明け前に起きる。"},
{"id": 24, "en": "together", "ja": "一緒に", "pronunciation": "təˈɡeðər", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👥", "ex": "We travel together to the castle.", "tr": "私たちは一緒に城へ旅をする。"},
{"id": 25, "en": "beautiful", "ja": "美しい", "pronunciation": "ˈbjuːtɪfəl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🌸", "ex": "The garden is beautiful in the moonlight.", "tr": "月明かりの中、庭は美しい。"},
{"id": 26, "en": "necessary", "ja": "必要な", "pronunciation": "ˈnesəseri", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧰", "ex": "A strong rope is necessary for the climb.", "tr": "登るには丈夫なロープが必要だ。"},
{"id": 27, "en": "remember", "ja": "覚えている", "pronunciation": "rɪˈmembər", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧠", "ex": "I remember the way home.", "tr": "私は家への道を覚えている。"},
{"id": 28, "en": "decide", "ja": "決める", "pronunciation": "dɪˈsaɪd", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⚖️", "ex": "He cannot decide which path to take.", "tr": "彼はどの道を行くか決められない。"},
{"id": 29, "en": "continue", "ja": "続ける", "pronunciation": "kənˈtɪnjuː", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "▶️", "ex": "The knights continue their journey at dawn.", "tr": "騎士たちは夜明けに旅を続ける。"},
{"id": 30, "en": "arrive", "ja": "到着する", "pronunciation": "əˈraɪv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏁", "ex": "The travelers arrive at the gate at night.", "tr": "旅人たちは夜に門へ到着する。"},
{"id": 31, "en": "possible", "ja": "可能な", "pronunciation": "ˈpɑːsəbəl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "✅", "ex": "Is it possible to cross the river?", "tr": "川を渡ることは可能だろうか。"},
{"id": 32, "en": "future", "ja": "未来", "pronunciation": "ˈfjuːtʃər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔮", "ex": "The oracle sees the future in a crystal.", "tr": "神託者は水晶の中に未来を見る。"},
{"id": 33, "en": "problem", "ja": "問題", "pronunciation": "ˈprɑːbləm", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "❓", "ex": "The villagers have a problem with the well.", "tr": "村人たちは井戸の問題を抱えている。"},
{"id": 34, "en": "reason", "ja": "理由", "pronunciation": "ˈriːzən", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💡", "ex": "There is a reason for the strange light.", "tr": "あの不思議な光には理由がある。"},
{"id": 35, "en": "experience", "ja": "経験", "pronunciation": "ɪkˈspɪriəns", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎖️", "ex": "The old knight has years of experience.", "tr": "老騎士には長年の経験がある。"},
{"id": 36, "en": "learn", "ja": "学ぶ", "pronunciation": "lɜːrn", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎓", "ex": "Young mages learn spells at the tower.", "tr": "若い魔法使いは塔で呪文を学ぶ。"},
{"id": 37, "en": "difficult", "ja": "難しい", "pronunciation": "ˈdɪfɪkəlt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧗", "ex": "The spell is difficult to cast.", "tr": "その呪文は唱えるのが難しい。"},
{"id": 38, "en": "travel", "ja": "旅する", "pronunciation": "ˈtrævəl", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧭", "ex": "Merchants travel across the desert.", "tr": "商人たちは砂漠を旅する。"},
{"id": 39, "en": "believe", "ja": "信じる", "pronunciation": "bɪˈliːv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🙏", "ex": "I believe in the power of words.", "tr": "私は言葉の力を信じている。"},
{"id": 40, "en": "forget", "ja": "忘れる", "pronunciation": "fərˈɡet", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💭", "ex": "Do not forget your lantern.", "tr": "ランタンを忘れないで。"},
{"id": 41, "en": "improve", "ja": "改善する", "pronunciation": "ɪmˈpruːv", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "📈", "ex": "With daily practice, the young mage began to improve.", "tr": "毎日の練習で、若い魔法使いは上達し始めた。"},
{"id": 42, "en": "consider", "ja": "検討する", "pronunciation": "kənˈsɪdər", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🤔", "ex": "The king will consider the offer carefully.", "tr": "王はその申し出をじっくり検討する。"},
{"id": 43, "en": "suggest", "ja": "提案する", "pronunciation": "səɡˈdʒest", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "💬", "ex": "The old wizard suggested a safer route through the forest.", "tr": "老魔法使いは、森を抜ける安全な道を提案した。"},
{"id": 44, "en": "require", "ja": "必要とする", "pronunciation": "rɪˈkwaɪər", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "📋", "ex": "This spell requires a rare crystal.", "tr": "この呪文には珍しい水晶が必要だ。"},
{"id": 45, "en": "develop", "ja": "発展する", "pronunciation": "dɪˈveləp", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🌱", "ex": "The small village developed into a great magical city.", "tr": "小さな村は、偉大な魔法都市へと発展した。"},
{"id": 46, "en": "increase", "ja": "増える", "pronunciation": "ɪnˈkriːs", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "⬆️", "ex": "The number of stars increases every night.", "tr": "星の数は毎晩増えていく。"},
{"id": 47, "en": "reduce", "ja": "減らす", "pronunciation": "rɪˈduːs", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "⬇️", "ex": "The shield reduces the damage from the fire.", "tr": "盾は炎によるダメージを減らす。"},
{"id": 48, "en": "environment", "ja": "環境", "pronunciation": "ɪnˈvaɪrənmənt", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🌳", "ex": "The elves work hard to protect their forest environment.", "tr": "エルフたちは、森の環境を守るために懸命に働く。"},
{"id": 49, "en": "relationship", "ja": "関係", "pronunciation": "rɪˈleɪʃənʃɪp", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🔗", "ex": "The two kingdoms have a strong relationship.", "tr": "二つの王国は強い関係で結ばれている。"},
{"id": 50, "en": "opportunity", "ja": "機会", "pronunciation": "ˌɑːpərˈtuːnəti", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🚪", "ex": "A rare opportunity appeared before the young knight.", "tr": "若い騎士の前に、めったにない好機が現れた。"},
{"id": 51, "en": "responsibility", "ja": "責任", "pronunciation": "rɪˌspɑːnsəˈbɪləti", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🛡️", "ex": "A guardian carries a heavy responsibility.", "tr": "守護者は重い責任を背負っている。"},
{"id": 52, "en": "effective", "ja": "効果的な", "pronunciation": "ɪˈfektɪv", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🎯", "ex": "The potion was effective against the poison.", "tr": "その薬は毒に効果的だった。"},
{"id": 53, "en": "available", "ja": "利用できる", "pronunciation": "əˈveɪləbəl", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🟢", "ex": "Two rooms are available at the inn.", "tr": "宿には二部屋空いている。"},
{"id": 54, "en": "achieve", "ja": "達成する", "pronunciation": "əˈtʃiːv", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🏆", "ex": "She worked for years to achieve her dream.", "tr": "彼女は夢を達成するために何年も努力した。"},
{"id": 55, "en": "compare", "ja": "比べる", "pronunciation": "kəmˈper", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🔍", "ex": "The merchant compared the two swords carefully.", "tr": "商人は二本の剣を注意深く比べた。"},
{"id": 56, "en": "describe", "ja": "描写する", "pronunciation": "dɪˈskraɪb", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🖊️", "ex": "The traveler described the dragon to the villagers.", "tr": "旅人は村人たちにドラゴンの様子を語った。"},
{"id": 57, "en": "influence", "ja": "影響", "pronunciation": "ˈɪnfluəns", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🌊", "ex": "The moon has a strong influence on the tides.", "tr": "月は潮に強い影響を与える。"},
{"id": 58, "en": "purpose", "ja": "目的", "pronunciation": "ˈpɜːrpəs", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🗺️", "ex": "What is the purpose of this ancient tower?", "tr": "この古い塔の目的は何だろう。"},
{"id": 59, "en": "popular", "ja": "人気のある", "pronunciation": "ˈpɑːpjələr", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🌟", "ex": "The bard is popular in every town.", "tr": "その吟遊詩人はどの町でも人気だ。"},
{"id": 60, "en": "challenge", "ja": "挑戦", "pronunciation": "ˈtʃælɪndʒ", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "⚔️", "ex": "The young hero accepted the challenge.", "tr": "若い勇者はその挑戦を受けた。"},
{"id": 61, "en": "implement", "ja": "実行する", "pronunciation": "ˈɪmplɪment", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "⚙️", "ex": "The council will implement the new plan tomorrow.", "tr": "評議会は明日、新しい計画を実行する。"},
{"id": 62, "en": "facilitate", "ja": "円滑にする", "pronunciation": "fəˈsɪlɪteɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🌉", "ex": "A magic bridge facilitates trade between the two kingdoms.", "tr": "魔法の橋が、二つの王国の交易を円滑にする。"},
{"id": 63, "en": "significant", "ja": "著しい", "pronunciation": "sɪɡˈnɪfɪkənt", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📊", "ex": "The wizard noticed a significant change in the stars.", "tr": "魔法使いは星に著しい変化を見つけた。"},
{"id": 64, "en": "potential", "ja": "可能性", "pronunciation": "pəˈtenʃəl", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🌰", "ex": "The boy has great potential as a mage.", "tr": "その少年には魔法使いとして大きな可能性がある。"},
{"id": 65, "en": "perspective", "ja": "視点", "pronunciation": "pərˈspektɪv", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🔭", "ex": "From the tower, she saw the city from a new perspective.", "tr": "塔の上から、彼女は町を新しい視点で見た。"},
{"id": 66, "en": "alternative", "ja": "代わりの", "pronunciation": "ɔːlˈtɜːrnətɪv", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "🛤️", "ex": "When the gate was sealed, they found an alternative route.", "tr": "門が封じられたとき、彼らは代わりの道を見つけた。"},
{"id": 67, "en": "consequence", "ja": "結果", "pronunciation": "ˈkɑːnsəkwens", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "💥", "ex": "The wizard faced the consequence of his forbidden spell.", "tr": "魔法使いは、禁断の呪文の報いに向き合った。"},
{"id": 68, "en": "accurate", "ja": "正確な", "pronunciation": "ˈækjərət", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📐", "ex": "The old map is accurate down to the last river.", "tr": "その古い地図は、小川ひとつまで正確だ。"},
{"id": 69, "en": "efficient", "ja": "効率的な", "pronunciation": "ɪˈfɪʃənt", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "⚡", "ex": "The dwarves built an efficient machine to mine the crystals.", "tr": "ドワーフたちは、水晶を掘るための効率的な機械を作った。"},
{"id": 70, "en": "strategy", "ja": "戦略", "pronunciation": "ˈstrætədʒi", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "♟️", "ex": "The queen studied the map and planned a bold strategy.", "tr": "女王は地図を調べ、大胆な戦略を立てた。"},
{"id": 71, "en": "evaluate", "ja": "評価する", "pronunciation": "ɪˈvæljueɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "📝", "ex": "The judges evaluate each mage's skill carefully.", "tr": "審査員は、それぞれの魔法使いの腕を慎重に評価する。"},
{"id": 72, "en": "analyze", "ja": "分析する", "pronunciation": "ˈænəlaɪz", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🔬", "ex": "The scholar analyzed the ancient runes for weeks.", "tr": "学者は何週間も古代のルーンを分析した。"},
{"id": 73, "en": "establish", "ja": "設立する", "pronunciation": "ɪˈstæblɪʃ", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🏛️", "ex": "The heroes established a guild in the northern city.", "tr": "勇者たちは北の町にギルドを設立した。"},
{"id": 74, "en": "maintain", "ja": "維持する", "pronunciation": "meɪnˈteɪn", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🔧", "ex": "The guards maintain the walls of the castle.", "tr": "衛兵たちは城壁を維持している。"},
{"id": 75, "en": "enhance", "ja": "高める", "pronunciation": "ɪnˈhæns", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "✨", "ex": "This gem can enhance the power of a spell.", "tr": "この宝石は呪文の力を高めることができる。"},
{"id": 76, "en": "criteria", "ja": "基準", "pronunciation": "kraɪˈtɪriə", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "📏", "ex": "The knight met all the criteria for the royal order.", "tr": "騎士は王の騎士団の基準をすべて満たした。"},
{"id": 77, "en": "priority", "ja": "優先事項", "pronunciation": "praɪˈɔːrəti", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🥇", "ex": "Protecting the villagers is our first priority.", "tr": "村人を守ることが、私たちの最優先事項だ。"},
{"id": 78, "en": "comprehensive", "ja": "包括的な", "pronunciation": "ˌkɑːmprɪˈhensɪv", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📚", "ex": "The library holds a comprehensive guide to magic.", "tr": "図書館には魔法の包括的な案内書がある。"},
{"id": 79, "en": "demonstrate", "ja": "実演する", "pronunciation": "ˈdemənstreɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🎤", "ex": "The master will demonstrate the spell to the students.", "tr": "師匠は生徒たちに呪文を実演してみせる。"},
{"id": 80, "en": "assumption", "ja": "前提", "pronunciation": "əˈsʌmpʃən", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🎭", "ex": "Their plan was based on a false assumption.", "tr": "彼らの計画は誤った前提に基づいていた。"},
{"id": 81, "en": "leverage", "ja": "活用する", "pronunciation": "ˈlevərɪdʒ", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🏗️", "ex": "The merchant guild leveraged its alliances to expand into new markets.", "tr": "商人ギルドは、同盟関係を活用して新しい市場へ進出した。"},
{"id": 82, "en": "mitigate", "ja": "和らげる", "pronunciation": "ˈmɪtɪɡeɪt", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧯", "ex": "The archmage raised a barrier to mitigate the damage of the dragon's fire.", "tr": "大魔導師は、竜の炎の被害を和らげる結界を張った。"},
{"id": 83, "en": "acquisition", "ja": "買収", "pronunciation": "ˌækwɪˈzɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🏦", "ex": "The acquisition of the rival guild doubled the kingdom's trade.", "tr": "ライバルのギルドの買収が、王国の交易を倍にした。"},
{"id": 84, "en": "stakeholder", "ja": "利害関係者", "pronunciation": "ˈsteɪkhoʊldər", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧑‍🤝‍🧑", "ex": "Every stakeholder gathered at the round table to discuss the kingdom's future.", "tr": "すべての利害関係者が円卓に集まり、王国の未来を話し合った。"},
{"id": 85, "en": "compliance", "ja": "順守", "pronunciation": "kəmˈplaɪəns", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📜", "ex": "The guild ensured full compliance with the royal safety rules.", "tr": "ギルドは、王の安全規則への完全な順守を徹底した。"},
{"id": 86, "en": "revenue", "ja": "収益", "pronunciation": "ˈrevənuː", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "💰", "ex": "The harbor's revenue grew after the new ships arrived.", "tr": "新しい船が着いてから、港の収益は伸びた。"},
{"id": 87, "en": "disruption", "ja": "混乱", "pronunciation": "dɪsˈrʌpʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🌪️", "ex": "A sudden storm caused serious disruption to the trade routes.", "tr": "突然の嵐が、交易路に深刻な混乱を引き起こした。"},
{"id": 88, "en": "sustainable", "ja": "持続可能な", "pronunciation": "səˈsteɪnəbəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "♻️", "ex": "The elves designed a sustainable city that grows together with the forest.", "tr": "エルフたちは、森とともに育つ持続可能な都市を設計した。"},
{"id": 89, "en": "negotiation", "ja": "交渉", "pronunciation": "nɪˌɡoʊʃiˈeɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🕊️", "ex": "After a long negotiation, the two kingdoms signed a peace treaty.", "tr": "長い交渉の末、二つの王国は和平条約に署名した。"},
{"id": 90, "en": "collaboration", "ja": "協力", "pronunciation": "kəˌlæbəˈreɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧩", "ex": "The collaboration of mages and smiths produced a legendary sword.", "tr": "魔法使いと鍛冶師の協力が、伝説の剣を生み出した。"},
{"id": 91, "en": "proactively", "ja": "先手を打って", "pronunciation": "ˌproʊˈæktɪvli", "pos": "副詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🚀", "ex": "The captain proactively reinforced the walls before the siege.", "tr": "隊長は包囲される前に、先手を打って城壁を補強した。"},
{"id": 92, "en": "substantial", "ja": "かなりの", "pronunciation": "səbˈstænʃəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧱", "ex": "The dragon's hoard held a substantial amount of gold.", "tr": "竜の宝の山には、かなりの量の金貨があった。"},
{"id": 93, "en": "constraint", "ja": "制約", "pronunciation": "kənˈstreɪnt", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "⛓️", "ex": "The mages worked within strict constraints of time and mana.", "tr": "魔法使いたちは、時間と魔力の厳しい制約の中で働いた。"},
{"id": 94, "en": "incentive", "ja": "報奨", "pronunciation": "ɪnˈsentɪv", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🎁", "ex": "The king offered a golden incentive to anyone who could break the curse.", "tr": "王は、呪いを解いた者に金の報奨を約束した。"},
{"id": 95, "en": "scalable", "ja": "拡張可能な", "pronunciation": "ˈskeɪləbəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📶", "ex": "The guild built a scalable system that could grow with the city.", "tr": "ギルドは、街とともに拡大できる拡張可能な仕組みを作った。"},
{"id": 96, "en": "benchmark", "ja": "指標", "pronunciation": "ˈbentʃmɑːrk", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📍", "ex": "The old champion's record became the benchmark for every young knight.", "tr": "老いた王者の記録は、すべての若い騎士の目標となる指標になった。"},
{"id": 97, "en": "liability", "ja": "負債", "pronunciation": "ˌlaɪəˈbɪləti", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "💸", "ex": "An unpaid debt became a heavy liability for the merchant.", "tr": "未払いの借金は、商人にとって重い負債となった。"},
{"id": 98, "en": "contingency", "ja": "不測の事態", "pronunciation": "kənˈtɪndʒənsi", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🆘", "ex": "The general prepared a contingency plan in case the bridge fell.", "tr": "将軍は、橋が落ちた場合に備えて不測の事態への計画を用意した。"},
{"id": 99, "en": "deliverable", "ja": "成果物", "pronunciation": "dɪˈlɪvərəbəl", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📦", "ex": "Each apprentice submitted the final deliverable before the deadline.", "tr": "弟子たちはそれぞれ、期限前に成果物を提出した。"},
{"id": 100, "en": "streamline", "ja": "効率化する", "pronunciation": "ˈstriːmlaɪn", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🌀", "ex": "The guildmaster streamlined the process to save time.", "tr": "ギルド長は時間を節約するため、手順を効率化した。"}];
(function(){const s=new Set();WORDS.forEach(x=>{if(s.has(x.id))console.warn("単語のIDが重複しています:",x.id,x.en);s.add(x.id)});const m=Math.max(...s);if(m>=101)console.info("次に使うID: "+(m+1))})();
