/* 単語データ（現在：COMMON 100語、UNCOMMON 100語、RARE〜LEGENDARY 各20語 = 260語。目標は各100語）
   ── IDのルール ──────────────────────────────────────────
   ・id は「通し番号」。レアリティや並び順とは無関係で、一度使った番号は二度と使わない（永久欠番）。
   ・新しい単語は、必ず「次のID」を使う（下の「次に使うID」）。どのレアリティの単語でも、番号は続きから。
   ・単語を消しても、番号は詰めない（セーブデータの owned / mastery は id で保存されている）。
   ・レアリティを変えても、id は変えない。
   ・図鑑の並びは、この配列の並び。同じレアリティの単語は、まとめて並べておく（途中に追加してよい）。
   ・ex は、カードゲーム風の一文（そのまま例文として使う）。tr はその日本語訳。
   ・カード画像は assets/cards/単語(en).webp（id ではなく en で対応）。
   次に使うID：261 */
const WORDS=[{"id": 1, "en": "apple", "ja": "りんご", "pronunciation": "ˈæpəl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍎", "ex": "The knight eats a red apple.", "tr": "騎士は赤いりんごを食べる。"},
{"id": 2, "en": "book", "ja": "本", "pronunciation": "bʊk", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "📖", "ex": "She reads a big book.", "tr": "少女は大きな本を読んでいる。"},
{"id": 3, "en": "cat", "ja": "猫", "pronunciation": "kæt", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐈", "ex": "The black cat sleeps on a stone wall.", "tr": "黒猫が石壁の上で眠っている。"},
{"id": 4, "en": "dog", "ja": "犬", "pronunciation": "dɔːɡ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐕", "ex": "The brave dog guards the gate.", "tr": "勇敢な犬が門を守っている。"},
{"id": 5, "en": "house", "ja": "家", "pronunciation": "haʊs", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏠", "ex": "A small house stands by the lake.", "tr": "湖のそばに小さな家が立っている。"},
{"id": 6, "en": "school", "ja": "学校", "pronunciation": "skuːl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏫", "ex": "The children walk to the old school.", "tr": "子どもたちは古い学校へ歩いていく。"},
{"id": 7, "en": "water", "ja": "水", "pronunciation": "ˈwɔːtər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "💧", "ex": "The traveler drinks cold water from a spring.", "tr": "旅人が泉の冷たい水を飲む。"},
{"id": 8, "en": "food", "ja": "食べ物", "pronunciation": "fuːd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍲", "ex": "The cook makes hot food for the guests.", "tr": "料理人が客のために温かい食べ物を作る。"},
{"id": 9, "en": "friend", "ja": "友達", "pronunciation": "frend", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🤝", "ex": "The hero helps his best friend.", "tr": "勇者は親友を助ける。"},
{"id": 10, "en": "family", "ja": "家族", "pronunciation": "ˈfæməli", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👨‍👩‍👧", "ex": "The family sits around a warm fire.", "tr": "家族が暖かい火のまわりに座っている。"},
{"id": 11, "en": "sun", "ja": "太陽", "pronunciation": "sʌn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "☀️", "ex": "The sun rises over the castle.", "tr": "太陽が城の上に昇る。"},
{"id": 12, "en": "moon", "ja": "月", "pronunciation": "muːn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌙", "ex": "The moon shines on the lake.", "tr": "月が湖を照らしている。"},
{"id": 13, "en": "car", "ja": "車", "pronunciation": "kɑːr", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🚗", "ex": "The old car stops at the bridge.", "tr": "古い車が橋の前で止まる。"},
{"id": 14, "en": "go", "ja": "行く", "pronunciation": "ɡoʊ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🚶", "ex": "We go to the forest at dawn.", "tr": "私たちは夜明けに森へ行く。"},
{"id": 15, "en": "come", "ja": "来る", "pronunciation": "kʌm", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "👋", "ex": "Come here and see the stars.", "tr": "ここに来て、星を見て。"},
{"id": 16, "en": "eat", "ja": "食べる", "pronunciation": "iːt", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🍽️", "ex": "The giant likes to eat bread.", "tr": "巨人はパンを食べるのが好きだ。"},
{"id": 17, "en": "drink", "ja": "飲む", "pronunciation": "drɪŋk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🥤", "ex": "Drink this tea and rest.", "tr": "このお茶を飲んで休みなさい。"},
{"id": 18, "en": "sleep", "ja": "眠る", "pronunciation": "sliːp", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "😴", "ex": "The baby dragon sleeps all day.", "tr": "子どものドラゴンは一日中眠っている。"},
{"id": 19, "en": "happy", "ja": "幸せな", "pronunciation": "ˈhæpi", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "😊", "ex": "The princess is happy today.", "tr": "姫は今日、幸せそうだ。"},
{"id": 20, "en": "big", "ja": "大きい", "pronunciation": "bɪɡ", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🐘", "ex": "A big bird flies above the town.", "tr": "大きな鳥が町の上を飛んでいる。"},
{"id": 101, "en": "bird", "ja": "鳥", "pronunciation": "bɜːrd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐦", "ex": "A bird sings on the castle wall.", "tr": "鳥が城壁の上で歌っている。"},
{"id": 102, "en": "fish", "ja": "魚", "pronunciation": "fɪʃ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐟", "ex": "The fish swims in the clear lake.", "tr": "魚が澄んだ湖を泳いでいる。"},
{"id": 103, "en": "horse", "ja": "馬", "pronunciation": "hɔːrs", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🐎", "ex": "The knight rides a white horse.", "tr": "騎士が白い馬に乗っている。"},
{"id": 104, "en": "tree", "ja": "木", "pronunciation": "triː", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌳", "ex": "A tall tree stands by the river.", "tr": "背の高い木が川のそばに立っている。"},
{"id": 105, "en": "flower", "ja": "花", "pronunciation": "ˈflaʊər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌼", "ex": "She picks a flower in the garden.", "tr": "少女は庭で花を摘む。"},
{"id": 106, "en": "river", "ja": "川", "pronunciation": "ˈrɪvər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏞️", "ex": "The river runs through the forest.", "tr": "川が森の中を流れていく。"},
{"id": 107, "en": "mountain", "ja": "山", "pronunciation": "ˈmaʊntən", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "⛰️", "ex": "The dragon sleeps on the mountain.", "tr": "ドラゴンが山の上で眠っている。"},
{"id": 108, "en": "sea", "ja": "海", "pronunciation": "siː", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌊", "ex": "The ship sails across the sea.", "tr": "船が海を渡っていく。"},
{"id": 109, "en": "star", "ja": "星", "pronunciation": "stɑːr", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "💫", "ex": "A star shines above the tower.", "tr": "塔の上に星が輝いている。"},
{"id": 110, "en": "rain", "ja": "雨", "pronunciation": "reɪn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌧️", "ex": "The rain falls on the old town.", "tr": "雨が古い町に降っている。"},
{"id": 111, "en": "wind", "ja": "風", "pronunciation": "wɪnd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "💨", "ex": "A cold wind blows from the north.", "tr": "冷たい風が北から吹いてくる。"},
{"id": 112, "en": "snow", "ja": "雪", "pronunciation": "snoʊ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "❄️", "ex": "Snow covers the mountain path.", "tr": "雪が山道をおおっている。"},
{"id": 113, "en": "fire", "ja": "火", "pronunciation": "ˈfaɪər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🔥", "ex": "The wizard lights a small fire.", "tr": "魔法使いが小さな火をおこす。"},
{"id": 114, "en": "bread", "ja": "パン", "pronunciation": "bred", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍞", "ex": "The baker makes fresh bread.", "tr": "パン職人が焼きたてのパンを作る。"},
{"id": 115, "en": "milk", "ja": "牛乳", "pronunciation": "mɪlk", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🥛", "ex": "The cat drinks warm milk.", "tr": "猫が温かい牛乳を飲む。"},
{"id": 116, "en": "egg", "ja": "卵", "pronunciation": "eɡ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🥚", "ex": "The dragon guards a golden egg.", "tr": "ドラゴンが金の卵を守っている。"},
{"id": 117, "en": "rice", "ja": "米", "pronunciation": "raɪs", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍚", "ex": "The farmer grows rice in the field.", "tr": "農夫が畑で米を育てる。"},
{"id": 118, "en": "tea", "ja": "お茶", "pronunciation": "tiː", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍵", "ex": "The old man drinks hot tea.", "tr": "老人が熱いお茶を飲む。"},
{"id": 119, "en": "cake", "ja": "ケーキ", "pronunciation": "keɪk", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍰", "ex": "We eat cake at the party.", "tr": "私たちはパーティーでケーキを食べる。"},
{"id": 120, "en": "door", "ja": "ドア", "pronunciation": "dɔːr", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🚪", "ex": "The knight opens the heavy door.", "tr": "騎士が重いドアを開ける。"},
{"id": 121, "en": "window", "ja": "窓", "pronunciation": "ˈwɪndoʊ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🪟", "ex": "A light shines in the window.", "tr": "窓に明かりが灯っている。"},
{"id": 122, "en": "table", "ja": "テーブル", "pronunciation": "ˈteɪbəl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🍽️", "ex": "The map lies on the table.", "tr": "地図がテーブルの上にある。"},
{"id": 123, "en": "chair", "ja": "椅子", "pronunciation": "tʃer", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🪑", "ex": "A king sits on a golden chair.", "tr": "王が金の椅子に座っている。"},
{"id": 124, "en": "bed", "ja": "ベッド", "pronunciation": "bed", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🛏️", "ex": "The child goes to bed early.", "tr": "子どもは早くベッドに入る。"},
{"id": 125, "en": "room", "ja": "部屋", "pronunciation": "ruːm", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🛋️", "ex": "The room is warm and quiet.", "tr": "部屋は暖かくて静かだ。"},
{"id": 126, "en": "town", "ja": "町", "pronunciation": "taʊn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏘️", "ex": "A small town lies by the lake.", "tr": "小さな町が湖のそばにある。"},
{"id": 127, "en": "road", "ja": "道", "pronunciation": "roʊd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🛣️", "ex": "The road goes to the castle.", "tr": "その道は城へ続いている。"},
{"id": 128, "en": "bridge", "ja": "橋", "pronunciation": "brɪdʒ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌉", "ex": "A stone bridge crosses the river.", "tr": "石の橋が川にかかっている。"},
{"id": 129, "en": "castle", "ja": "城", "pronunciation": "ˈkæsəl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🏰", "ex": "The castle stands on a hill.", "tr": "城が丘の上にそびえている。"},
{"id": 130, "en": "king", "ja": "王", "pronunciation": "kɪŋ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🤴", "ex": "The king speaks to the people.", "tr": "王が民に語りかける。"},
{"id": 131, "en": "queen", "ja": "女王", "pronunciation": "kwiːn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👸", "ex": "The queen wears a silver crown.", "tr": "女王は銀の冠をかぶっている。"},
{"id": 132, "en": "boy", "ja": "少年", "pronunciation": "bɔɪ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👦", "ex": "The boy finds a magic key.", "tr": "少年が魔法の鍵を見つける。"},
{"id": 133, "en": "girl", "ja": "少女", "pronunciation": "ɡɜːrl", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👧", "ex": "The girl feeds a baby dragon.", "tr": "少女が子どものドラゴンにえさをやる。"},
{"id": 134, "en": "man", "ja": "男の人", "pronunciation": "mæn", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👨", "ex": "An old man walks on the road.", "tr": "老人が道を歩いている。"},
{"id": 135, "en": "woman", "ja": "女の人", "pronunciation": "ˈwʊmən", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👩", "ex": "A woman sells fruit at the market.", "tr": "女の人が市場で果物を売っている。"},
{"id": 136, "en": "baby", "ja": "赤ちゃん", "pronunciation": "ˈbeɪbi", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👶", "ex": "The baby sleeps in a small bed.", "tr": "赤ちゃんが小さなベッドで眠っている。"},
{"id": 137, "en": "teacher", "ja": "先生", "pronunciation": "ˈtiːtʃər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🧑‍🏫", "ex": "The teacher shows a map to the class.", "tr": "先生が生徒に地図を見せる。"},
{"id": 138, "en": "doctor", "ja": "医者", "pronunciation": "ˈdɑːktər", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🧑‍⚕️", "ex": "The doctor helps the hurt knight.", "tr": "医者が傷ついた騎士を助ける。"},
{"id": 139, "en": "sword", "ja": "剣", "pronunciation": "sɔːrd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🗡️", "ex": "The hero holds a bright sword.", "tr": "勇者が輝く剣を握っている。"},
{"id": 140, "en": "key", "ja": "鍵", "pronunciation": "kiː", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🔑", "ex": "A gold key opens the gate.", "tr": "金の鍵が門を開ける。"},
{"id": 141, "en": "box", "ja": "箱", "pronunciation": "bɑːks", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "📦", "ex": "A small box lies in the cave.", "tr": "小さな箱が洞くつに置かれている。"},
{"id": 142, "en": "bag", "ja": "かばん", "pronunciation": "bæɡ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "👜", "ex": "The traveler carries a heavy bag.", "tr": "旅人が重いかばんを運んでいる。"},
{"id": 143, "en": "hat", "ja": "帽子", "pronunciation": "hæt", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🎩", "ex": "The wizard wears a tall hat.", "tr": "魔法使いが背の高い帽子をかぶっている。"},
{"id": 144, "en": "night", "ja": "夜", "pronunciation": "naɪt", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌃", "ex": "The stars shine bright at night.", "tr": "夜には星が明るく輝く。"},
{"id": 145, "en": "morning", "ja": "朝", "pronunciation": "ˈmɔːrnɪŋ", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "🌅", "ex": "We wake up early in the morning.", "tr": "私たちは朝早く起きる。"},
{"id": 146, "en": "hand", "ja": "手", "pronunciation": "hænd", "pos": "名詞", "rarity": "COMMON", "stars": 1, "ic": "✋", "ex": "She holds a lantern in her hand.", "tr": "少女は手にランタンを持っている。"},
{"id": 147, "en": "see", "ja": "見る", "pronunciation": "siː", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "👀", "ex": "I can see the castle from here.", "tr": "ここから城が見える。"},
{"id": 148, "en": "walk", "ja": "歩く", "pronunciation": "wɔːk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🥾", "ex": "We walk along the river.", "tr": "私たちは川ぞいを歩く。"},
{"id": 149, "en": "run", "ja": "走る", "pronunciation": "rʌn", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🏃", "ex": "The fox runs into the forest.", "tr": "キツネが森へ走っていく。"},
{"id": 150, "en": "jump", "ja": "跳ぶ", "pronunciation": "dʒʌmp", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🤸", "ex": "The boy jumps over the stream.", "tr": "少年が小川を跳びこえる。"},
{"id": 151, "en": "swim", "ja": "泳ぐ", "pronunciation": "swɪm", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🏊", "ex": "The children swim in the lake.", "tr": "子どもたちが湖で泳ぐ。"},
{"id": 152, "en": "fly", "ja": "飛ぶ", "pronunciation": "flaɪ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🦅", "ex": "A dragon can fly above the clouds.", "tr": "ドラゴンは雲の上を飛べる。"},
{"id": 153, "en": "sit", "ja": "座る", "pronunciation": "sɪt", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "💺", "ex": "Please sit by the fire.", "tr": "火のそばに座ってください。"},
{"id": 154, "en": "open", "ja": "開ける", "pronunciation": "ˈoʊpən", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "📂", "ex": "Open the door and come in.", "tr": "ドアを開けて入ってきて。"},
{"id": 155, "en": "close", "ja": "閉める", "pronunciation": "kloʊz", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🔒", "ex": "Close the gate at night.", "tr": "夜には門を閉めなさい。"},
{"id": 156, "en": "read", "ja": "読む", "pronunciation": "riːd", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "📚", "ex": "I read a book every night.", "tr": "私は毎晩本を読む。"},
{"id": 157, "en": "write", "ja": "書く", "pronunciation": "raɪt", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "✍️", "ex": "She writes a letter to the king.", "tr": "少女は王に手紙を書く。"},
{"id": 158, "en": "sing", "ja": "歌う", "pronunciation": "sɪŋ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🎶", "ex": "The bard sings a happy song.", "tr": "吟遊詩人が楽しい歌を歌う。"},
{"id": 159, "en": "play", "ja": "遊ぶ", "pronunciation": "pleɪ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🎮", "ex": "The children play in the garden.", "tr": "子どもたちが庭で遊ぶ。"},
{"id": 160, "en": "help", "ja": "助ける", "pronunciation": "help", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🤲", "ex": "Please help me find my key.", "tr": "鍵を探すのを手伝って。"},
{"id": 161, "en": "make", "ja": "作る", "pronunciation": "meɪk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🔨", "ex": "Let's make a small boat.", "tr": "小さな舟を作ろう。"},
{"id": 162, "en": "buy", "ja": "買う", "pronunciation": "baɪ", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🛒", "ex": "I want to buy a new sword.", "tr": "新しい剣を買いたい。"},
{"id": 163, "en": "give", "ja": "与える", "pronunciation": "ɡɪv", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🎀", "ex": "The king gives a gold ring to the hero.", "tr": "王が勇者に金の指輪を贈る。"},
{"id": 164, "en": "love", "ja": "愛する", "pronunciation": "lʌv", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "❤️", "ex": "The knight loves his home.", "tr": "騎士は故郷を愛している。"},
{"id": 165, "en": "live", "ja": "住む", "pronunciation": "lɪv", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🏡", "ex": "Elves live in the old forest.", "tr": "エルフたちは古い森に住んでいる。"},
{"id": 166, "en": "work", "ja": "働く", "pronunciation": "wɜːrk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "💼", "ex": "The dwarves work in the mine.", "tr": "ドワーフたちが鉱山で働いている。"},
{"id": 167, "en": "listen", "ja": "聞く", "pronunciation": "ˈlɪsən", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "👂", "ex": "Listen to the sound of the sea.", "tr": "海の音に耳をすませて。"},
{"id": 168, "en": "speak", "ja": "話す", "pronunciation": "spiːk", "pos": "動詞", "rarity": "COMMON", "stars": 1, "ic": "🗣️", "ex": "The wise owl can speak.", "tr": "賢いフクロウは話すことができる。"},
{"id": 169, "en": "small", "ja": "小さい", "pronunciation": "smɔːl", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🐜", "ex": "A small fox hides in the grass.", "tr": "小さなキツネが草の中にかくれている。"},
{"id": 170, "en": "new", "ja": "新しい", "pronunciation": "nuː", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🆕", "ex": "The knight has a new shield.", "tr": "騎士は新しい盾を持っている。"},
{"id": 171, "en": "old", "ja": "古い", "pronunciation": "oʊld", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🏚️", "ex": "The old tower is very tall.", "tr": "古い塔はとても高い。"},
{"id": 172, "en": "hot", "ja": "熱い", "pronunciation": "hɑːt", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🥵", "ex": "The soup is too hot.", "tr": "スープは熱すぎる。"},
{"id": 173, "en": "cold", "ja": "冷たい", "pronunciation": "koʊld", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🥶", "ex": "The lake is cold in winter.", "tr": "湖は冬に冷たい。"},
{"id": 174, "en": "fast", "ja": "速い", "pronunciation": "fæst", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🐇", "ex": "The horse is very fast.", "tr": "その馬はとても速い。"},
{"id": 175, "en": "strong", "ja": "強い", "pronunciation": "strɔːŋ", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "💪", "ex": "The strong knight lifts a big stone.", "tr": "強い騎士が大きな石を持ち上げる。"},
{"id": 176, "en": "good", "ja": "良い", "pronunciation": "ɡʊd", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "👍", "ex": "This is a good day for a trip.", "tr": "旅に出るのにいい日だ。"},
{"id": 177, "en": "red", "ja": "赤い", "pronunciation": "red", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🔴", "ex": "A red dragon flies over the town.", "tr": "赤いドラゴンが町の上を飛ぶ。"},
{"id": 178, "en": "blue", "ja": "青い", "pronunciation": "bluː", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "🔵", "ex": "The blue lake shines in the sun.", "tr": "青い湖が太陽の下で輝く。"},
{"id": 179, "en": "white", "ja": "白い", "pronunciation": "waɪt", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "⚪", "ex": "The snow is white and soft.", "tr": "雪は白くてやわらかい。"},
{"id": 180, "en": "black", "ja": "黒い", "pronunciation": "blæk", "pos": "形容詞", "rarity": "COMMON", "stars": 1, "ic": "⚫", "ex": "A black crow sits on the roof.", "tr": "黒いカラスが屋根にとまっている。"},
{"id": 21, "en": "important", "ja": "重要な", "pronunciation": "ɪmˈpɔːrtənt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⭐", "ex": "This old map is very important.", "tr": "この古い地図はとても大切だ。"},
{"id": 22, "en": "different", "ja": "違う", "pronunciation": "ˈdɪfrənt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔀", "ex": "Each door leads to a different world.", "tr": "どの扉も、違う世界につながっている。"},
{"id": 23, "en": "usually", "ja": "たいてい", "pronunciation": "ˈjuːʒuəli", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🕒", "ex": "The wizard usually wakes up before dawn.", "tr": "魔法使いはたいてい夜明け前に起きる。"},
{"id": 24, "en": "together", "ja": "一緒に", "pronunciation": "təˈɡeðər", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👥", "ex": "We travel together to the castle.", "tr": "私たちは一緒に城へ旅をする。"},
{"id": 25, "en": "beautiful", "ja": "美しい", "pronunciation": "ˈbjuːtɪfəl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🌸", "ex": "The garden is beautiful in the moonlight.", "tr": "月明かりの中、庭は美しい。"},
{"id": 26, "en": "necessary", "ja": "必要な", "pronunciation": "ˈnesəseri", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧰", "ex": "A strong rope is necessary for the climb.", "tr": "登るには丈夫なロープが必要だ。"},
{"id": 27, "en": "remember", "ja": "覚えている", "pronunciation": "rɪˈmembər", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧠", "ex": "I remember the way home.", "tr": "私は家への道を覚えている。"},
{"id": 28, "en": "decide", "ja": "決める", "pronunciation": "dɪˈsaɪd", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⚖️", "ex": "He cannot decide which path to take.", "tr": "彼はどの道を行くか決められない。"},
{"id": 29, "en": "continue", "ja": "続ける", "pronunciation": "kənˈtɪnjuː", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "▶️", "ex": "The knights continue their journey at dawn.", "tr": "騎士たちは夜明けに旅を続ける。"},
{"id": 30, "en": "arrive", "ja": "到着する", "pronunciation": "əˈraɪv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏁", "ex": "The travelers arrive at the gate at night.", "tr": "旅人たちは夜に門へ到着する。"},
{"id": 31, "en": "possible", "ja": "可能な", "pronunciation": "ˈpɑːsəbəl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "✅", "ex": "Is it possible to cross the river?", "tr": "川を渡ることは可能だろうか。"},
{"id": 32, "en": "future", "ja": "未来", "pronunciation": "ˈfjuːtʃər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔮", "ex": "The oracle sees the future in a crystal.", "tr": "神託者は水晶の中に未来を見る。"},
{"id": 33, "en": "problem", "ja": "問題", "pronunciation": "ˈprɑːbləm", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "❓", "ex": "The villagers have a problem with the well.", "tr": "村人たちは井戸の問題を抱えている。"},
{"id": 34, "en": "reason", "ja": "理由", "pronunciation": "ˈriːzən", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💡", "ex": "There is a reason for the strange light.", "tr": "あの不思議な光には理由がある。"},
{"id": 35, "en": "experience", "ja": "経験", "pronunciation": "ɪkˈspɪriəns", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎖️", "ex": "The old knight has years of experience.", "tr": "老騎士には長年の経験がある。"},
{"id": 36, "en": "learn", "ja": "学ぶ", "pronunciation": "lɜːrn", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎓", "ex": "Young mages learn spells at the tower.", "tr": "若い魔法使いは塔で呪文を学ぶ。"},
{"id": 37, "en": "difficult", "ja": "難しい", "pronunciation": "ˈdɪfɪkəlt", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧗", "ex": "The spell is difficult to cast.", "tr": "その呪文は唱えるのが難しい。"},
{"id": 38, "en": "travel", "ja": "旅する", "pronunciation": "ˈtrævəl", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧭", "ex": "Merchants travel across the desert.", "tr": "商人たちは砂漠を旅する。"},
{"id": 39, "en": "believe", "ja": "信じる", "pronunciation": "bɪˈliːv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🙏", "ex": "I believe in the power of words.", "tr": "私は言葉の力を信じている。"},
{"id": 40, "en": "forget", "ja": "忘れる", "pronunciation": "fərˈɡet", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💭", "ex": "Do not forget your lantern.", "tr": "ランタンを忘れないで。"},
{"id": 181, "en": "garden", "ja": "庭", "pronunciation": "ˈɡɑːrdn", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🌷", "ex": "Glowing flowers bloom in the secret garden.", "tr": "光る花が、秘密の庭に咲いている。"},
{"id": 182, "en": "kitchen", "ja": "台所", "pronunciation": "ˈkɪtʃɪn", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🍳", "ex": "The witch cooks a magic soup in the kitchen.", "tr": "魔女が台所で魔法のスープを作っている。"},
{"id": 183, "en": "market", "ja": "市場", "pronunciation": "ˈmɑːrkɪt", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏪", "ex": "The village market is full of strange fruit.", "tr": "村の市場は、不思議な果物でいっぱいだ。"},
{"id": 184, "en": "village", "ja": "村", "pronunciation": "ˈvɪlɪdʒ", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🛖", "ex": "A small village hides deep in the forest.", "tr": "小さな村が、森の奥にひっそりとある。"},
{"id": 185, "en": "forest", "ja": "森", "pronunciation": "ˈfɔːrɪst", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🌲", "ex": "Tiny lights dance in the dark forest.", "tr": "小さな光が、暗い森の中で舞っている。"},
{"id": 186, "en": "island", "ja": "島", "pronunciation": "ˈaɪlənd", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏝️", "ex": "A floating island appears above the clouds.", "tr": "浮かぶ島が、雲の上に現れる。"},
{"id": 187, "en": "desert", "ja": "砂漠", "pronunciation": "ˈdezərt", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏜️", "ex": "The travelers cross the hot desert at night.", "tr": "旅人たちは、夜に熱い砂漠を渡る。"},
{"id": 188, "en": "cave", "ja": "洞くつ", "pronunciation": "keɪv", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🕳️", "ex": "A blue light shines inside the cave.", "tr": "洞くつの中で、青い光が輝いている。"},
{"id": 189, "en": "tower", "ja": "塔", "pronunciation": "ˈtaʊər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🗼", "ex": "The wizard lives in the tallest tower.", "tr": "魔法使いは、いちばん高い塔に住んでいる。"},
{"id": 190, "en": "gate", "ja": "門", "pronunciation": "ɡeɪt", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⛩️", "ex": "The stone gate opens with a soft sound.", "tr": "石の門が、静かな音を立てて開く。"},
{"id": 191, "en": "ship", "ja": "船", "pronunciation": "ʃɪp", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚢", "ex": "A silver ship sails through the night sky.", "tr": "銀の船が、夜空を進んでいく。"},
{"id": 192, "en": "station", "ja": "駅", "pronunciation": "ˈsteɪʃn", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚉", "ex": "The old station is quiet at midnight.", "tr": "古い駅は、真夜中に静まりかえっている。"},
{"id": 193, "en": "hospital", "ja": "病院", "pronunciation": "ˈhɑːspɪtl", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏥", "ex": "The healer works at the hospital on the hill.", "tr": "癒し手は、丘の上の病院で働いている。"},
{"id": 194, "en": "library", "ja": "図書館", "pronunciation": "ˈlaɪbreri", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📕", "ex": "Ancient books sleep in the silent library.", "tr": "古い本たちが、静かな図書館で眠っている。"},
{"id": 195, "en": "ticket", "ja": "切符", "pronunciation": "ˈtɪkɪt", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎫", "ex": "She shows her ticket to the guard.", "tr": "少女は、衛兵に切符を見せる。"},
{"id": 196, "en": "map", "ja": "地図", "pronunciation": "mæp", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🗺️", "ex": "The old map shows a hidden island.", "tr": "古い地図が、隠された島を示している。"},
{"id": 197, "en": "letter", "ja": "手紙", "pronunciation": "ˈletər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "✉️", "ex": "A magic letter arrives at the window.", "tr": "魔法の手紙が、窓辺に届く。"},
{"id": 198, "en": "story", "ja": "物語", "pronunciation": "ˈstɔːri", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📖", "ex": "Grandma tells a story about a dragon.", "tr": "祖母が、ドラゴンの物語を話してくれる。"},
{"id": 199, "en": "dream", "ja": "夢", "pronunciation": "driːm", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🛌", "ex": "The boy has a dream about flying.", "tr": "少年は、空を飛ぶ夢を見る。"},
{"id": 200, "en": "question", "ja": "質問", "pronunciation": "ˈkwestʃən", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "❔", "ex": "The sphinx asks a difficult question.", "tr": "スフィンクスが、難しい質問をする。"},
{"id": 201, "en": "answer", "ja": "答え", "pronunciation": "ˈænsər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "☑️", "ex": "Only the brave hero knows the answer.", "tr": "勇敢な勇者だけが、その答えを知っている。"},
{"id": 202, "en": "number", "ja": "数", "pronunciation": "ˈnʌmbər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔢", "ex": "Choose a number between one and ten.", "tr": "一から十までの数を選んでください。"},
{"id": 203, "en": "color", "ja": "色", "pronunciation": "ˈkʌlər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎨", "ex": "The dragon changes color in the sun.", "tr": "ドラゴンは、日差しの中で色を変える。"},
{"id": 204, "en": "weather", "ja": "天気", "pronunciation": "ˈweðər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⛅", "ex": "The weather is good for a journey.", "tr": "旅に出るのによい天気だ。"},
{"id": 205, "en": "summer", "ja": "夏", "pronunciation": "ˈsʌmər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🌞", "ex": "Fireflies fill the air in summer.", "tr": "夏には、ホタルが空をうめつくす。"},
{"id": 206, "en": "winter", "ja": "冬", "pronunciation": "ˈwɪntər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⛄", "ex": "Snow falls softly in winter.", "tr": "冬には、雪がしずかに降る。"},
{"id": 207, "en": "holiday", "ja": "休日", "pronunciation": "ˈhɑːlədeɪ", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎉", "ex": "The whole town celebrates the holiday.", "tr": "町じゅうが、その休日を祝う。"},
{"id": 208, "en": "bicycle", "ja": "自転車", "pronunciation": "ˈbaɪsɪkl", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚲", "ex": "The boy rides a bicycle to school.", "tr": "少年は、自転車で学校へ行く。"},
{"id": 209, "en": "brother", "ja": "兄弟", "pronunciation": "ˈbrʌðər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👬", "ex": "My brother is a brave knight.", "tr": "私の兄は、勇敢な騎士だ。"},
{"id": 210, "en": "sister", "ja": "姉妹", "pronunciation": "ˈsɪstər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👭", "ex": "Her sister makes a magic potion.", "tr": "彼女の姉は、魔法の薬を作る。"},
{"id": 211, "en": "mother", "ja": "母", "pronunciation": "ˈmʌðər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👩‍👧", "ex": "His mother sings by the fire.", "tr": "彼の母は、火のそばで歌っている。"},
{"id": 212, "en": "father", "ja": "父", "pronunciation": "ˈfɑːðər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👨‍👦", "ex": "The father teaches his son to swim.", "tr": "父親は、息子に泳ぎを教える。"},
{"id": 213, "en": "umbrella", "ja": "傘", "pronunciation": "ʌmˈbrelə", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "☂️", "ex": "She opens an umbrella in the rain.", "tr": "少女は、雨の中で傘を開く。"},
{"id": 214, "en": "mirror", "ja": "鏡", "pronunciation": "ˈmɪrər", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🪞", "ex": "The mirror shows a strange world.", "tr": "鏡が、不思議な世界を映し出す。"},
{"id": 215, "en": "candle", "ja": "ろうそく", "pronunciation": "ˈkændl", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🕯️", "ex": "A single candle lights the dark room.", "tr": "一本のろうそくが、暗い部屋を照らす。"},
{"id": 216, "en": "ring", "ja": "指輪", "pronunciation": "rɪŋ", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💍", "ex": "The hero wears a ring of silver.", "tr": "勇者は、銀の指輪をはめている。"},
{"id": 217, "en": "crown", "ja": "王冠", "pronunciation": "kraʊn", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👑", "ex": "The prince puts on the golden crown.", "tr": "王子は、金の王冠をかぶる。"},
{"id": 218, "en": "shield", "ja": "盾", "pronunciation": "ʃiːld", "pos": "名詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🛡️", "ex": "The knight lifts his shield high.", "tr": "騎士は、盾を高くかかげる。"},
{"id": 219, "en": "wait", "ja": "待つ", "pronunciation": "weɪt", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⏳", "ex": "Please wait here until the moon rises.", "tr": "月が昇るまで、ここで待ってください。"},
{"id": 220, "en": "ask", "ja": "尋ねる", "pronunciation": "æsk", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🙋", "ex": "The traveler asks the way to the castle.", "tr": "旅人が、城への道を尋ねる。"},
{"id": 221, "en": "bring", "ja": "持ってくる", "pronunciation": "brɪŋ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧺", "ex": "Bring a lantern to the dark cave.", "tr": "暗い洞くつにランタンを持ってきて。"},
{"id": 222, "en": "carry", "ja": "運ぶ", "pronunciation": "ˈkæri", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎒", "ex": "The strong horse can carry two heavy bags.", "tr": "力強い馬は、重いかばんを二つ運べる。"},
{"id": 223, "en": "catch", "ja": "つかまえる", "pronunciation": "kætʃ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🎣", "ex": "The cat tries to catch a glowing fish.", "tr": "猫が、光る魚をつかまえようとする。"},
{"id": 224, "en": "choose", "ja": "選ぶ", "pronunciation": "tʃuːz", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👆", "ex": "You must choose one path today.", "tr": "今日、道を一つ選ばなければならない。"},
{"id": 225, "en": "climb", "ja": "登る", "pronunciation": "klaɪm", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🪜", "ex": "We climb the tall tower together.", "tr": "私たちは、一緒に高い塔を登る。"},
{"id": 226, "en": "cook", "ja": "料理する", "pronunciation": "kʊk", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧑‍🍳", "ex": "He cooks a fresh fish over the fire.", "tr": "彼は、火の上で新鮮な魚を料理する。"},
{"id": 227, "en": "cross", "ja": "渡る", "pronunciation": "krɔːs", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚸", "ex": "The children cross the bridge carefully.", "tr": "子どもたちは、注意して橋を渡る。"},
{"id": 228, "en": "dance", "ja": "踊る", "pronunciation": "dæns", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💃", "ex": "The fairies dance under the moon.", "tr": "妖精たちが、月の下で踊る。"},
{"id": 229, "en": "draw", "ja": "描く", "pronunciation": "drɔː", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🖌️", "ex": "She draws a dragon on the wall.", "tr": "少女は、壁にドラゴンを描く。"},
{"id": 230, "en": "enjoy", "ja": "楽しむ", "pronunciation": "ɪnˈdʒɔɪ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "😄", "ex": "We enjoy a warm meal at the inn.", "tr": "私たちは、宿で温かい食事を楽しむ。"},
{"id": 231, "en": "explain", "ja": "説明する", "pronunciation": "ɪkˈspleɪn", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📢", "ex": "The teacher explains the magic rules.", "tr": "先生が、魔法のルールを説明する。"},
{"id": 232, "en": "find", "ja": "見つける", "pronunciation": "faɪnd", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔎", "ex": "The boy finds a shining stone.", "tr": "少年は、光る石を見つける。"},
{"id": 233, "en": "follow", "ja": "ついていく", "pronunciation": "ˈfɑːloʊ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "👣", "ex": "Follow the light to the hidden door.", "tr": "光について、隠された扉まで行きなさい。"},
{"id": 234, "en": "join", "ja": "加わる", "pronunciation": "dʒɔɪn", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "➕", "ex": "Many heroes join the guild every year.", "tr": "毎年、多くの勇者がギルドに加わる。"},
{"id": 235, "en": "leave", "ja": "去る", "pronunciation": "liːv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🛫", "ex": "The knight must leave the village at dawn.", "tr": "騎士は、夜明けに村を去らなければならない。"},
{"id": 236, "en": "meet", "ja": "会う", "pronunciation": "miːt", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📅", "ex": "We meet at the old bridge at noon.", "tr": "私たちは、正午に古い橋で会う。"},
{"id": 237, "en": "protect", "ja": "守る", "pronunciation": "prəˈtekt", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔰", "ex": "The dragon protects the sleeping village.", "tr": "ドラゴンが、眠る村を守っている。"},
{"id": 238, "en": "save", "ja": "救う", "pronunciation": "seɪv", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⛑️", "ex": "The hero jumps in to save the child.", "tr": "勇者は、子どもを救うために飛びこむ。"},
{"id": 239, "en": "search", "ja": "探す", "pronunciation": "sɜːrtʃ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔍", "ex": "They search the forest for the lost key.", "tr": "彼らは、なくした鍵を求めて森を探す。"},
{"id": 240, "en": "send", "ja": "送る", "pronunciation": "send", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📨", "ex": "The wizard sends a message by bird.", "tr": "魔法使いは、鳥で伝言を送る。"},
{"id": 241, "en": "share", "ja": "分け合う", "pronunciation": "ʃer", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🫂", "ex": "The friends share bread and warm tea.", "tr": "友人たちは、パンと温かいお茶を分け合う。"},
{"id": 242, "en": "show", "ja": "見せる", "pronunciation": "ʃoʊ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📽️", "ex": "The guide shows us the secret path.", "tr": "案内人が、私たちに秘密の道を見せる。"},
{"id": 243, "en": "teach", "ja": "教える", "pronunciation": "tiːtʃ", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏫", "ex": "The old knight teaches young soldiers.", "tr": "老騎士が、若い兵士たちを教える。"},
{"id": 244, "en": "visit", "ja": "訪れる", "pronunciation": "ˈvɪzɪt", "pos": "動詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🧳", "ex": "Many travelers visit the ancient temple.", "tr": "多くの旅人が、古代の神殿を訪れる。"},
{"id": 245, "en": "careful", "ja": "注意深い", "pronunciation": "ˈkerfl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚧", "ex": "Be careful on the icy bridge.", "tr": "凍った橋では、気をつけて。"},
{"id": 246, "en": "dangerous", "ja": "危険な", "pronunciation": "ˈdeɪndʒərəs", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "⚠️", "ex": "The dark forest is very dangerous.", "tr": "暗い森はとても危険だ。"},
{"id": 247, "en": "quiet", "ja": "静かな", "pronunciation": "ˈkwaɪət", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🤫", "ex": "The night is calm and quiet.", "tr": "夜は穏やかで静かだ。"},
{"id": 248, "en": "brave", "ja": "勇敢な", "pronunciation": "breɪv", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🦁", "ex": "The brave girl enters the cave.", "tr": "勇敢な少女が、洞くつに入る。"},
{"id": 249, "en": "clever", "ja": "賢い", "pronunciation": "ˈklevər", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🦊", "ex": "A clever fox solves the puzzle.", "tr": "賢いキツネが、なぞを解く。"},
{"id": 250, "en": "empty", "ja": "空の", "pronunciation": "ˈempti", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🗑️", "ex": "The old castle is empty now.", "tr": "古い城は、今は空っぽだ。"},
{"id": 251, "en": "famous", "ja": "有名な", "pronunciation": "ˈfeɪməs", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "📣", "ex": "The famous bard sings in the town.", "tr": "有名な吟遊詩人が、町で歌う。"},
{"id": 252, "en": "heavy", "ja": "重い", "pronunciation": "ˈhevi", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🏋️", "ex": "The knight carries a heavy sword.", "tr": "騎士は、重い剣を持っている。"},
{"id": 253, "en": "tired", "ja": "疲れた", "pronunciation": "ˈtaɪərd", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "😪", "ex": "The tired traveler falls asleep quickly.", "tr": "疲れた旅人は、すぐに眠りに落ちる。"},
{"id": 254, "en": "safe", "ja": "安全な", "pronunciation": "seɪf", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔐", "ex": "The village is safe from the storm.", "tr": "村は、嵐から守られている。"},
{"id": 255, "en": "ready", "ja": "準備ができた", "pronunciation": "ˈredi", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🙌", "ex": "The team is ready for the journey.", "tr": "一行は、旅の準備ができている。"},
{"id": 256, "en": "special", "ja": "特別な", "pronunciation": "ˈspeʃl", "pos": "形容詞", "rarity": "UNCOMMON", "stars": 2, "ic": "💎", "ex": "This is a special day for the kingdom.", "tr": "今日は、王国にとって特別な日だ。"},
{"id": 257, "en": "always", "ja": "いつも", "pronunciation": "ˈɔːlweɪz", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "♾️", "ex": "The owl always watches the forest.", "tr": "フクロウは、いつも森を見守っている。"},
{"id": 258, "en": "never", "ja": "決して〜ない", "pronunciation": "ˈnevər", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🚫", "ex": "The old wizard never lies.", "tr": "老魔法使いは、決してうそをつかない。"},
{"id": 259, "en": "suddenly", "ja": "突然", "pronunciation": "ˈsʌdənli", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "‼️", "ex": "Suddenly, the sky turns bright red.", "tr": "突然、空が真っ赤に染まる。"},
{"id": 260, "en": "finally", "ja": "ついに", "pronunciation": "ˈfaɪnəli", "pos": "副詞", "rarity": "UNCOMMON", "stars": 2, "ic": "🔚", "ex": "Finally, the hero reaches the tower.", "tr": "ついに、勇者は塔にたどり着く。"},
{"id": 41, "en": "improve", "ja": "改善する", "pronunciation": "ɪmˈpruːv", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "📈", "ex": "With daily practice, the young mage began to improve.", "tr": "毎日の練習で、若い魔法使いは上達し始めた。"},
{"id": 42, "en": "consider", "ja": "検討する", "pronunciation": "kənˈsɪdər", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🤔", "ex": "The king will consider the offer carefully.", "tr": "王はその申し出をじっくり検討する。"},
{"id": 43, "en": "suggest", "ja": "提案する", "pronunciation": "səɡˈdʒest", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "💬", "ex": "The old wizard suggested a safer route through the forest.", "tr": "老魔法使いは、森を抜ける安全な道を提案した。"},
{"id": 44, "en": "require", "ja": "必要とする", "pronunciation": "rɪˈkwaɪər", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "📋", "ex": "This spell requires a rare crystal.", "tr": "この呪文には珍しい水晶が必要だ。"},
{"id": 45, "en": "develop", "ja": "発展する", "pronunciation": "dɪˈveləp", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🌱", "ex": "The small village developed into a great magical city.", "tr": "小さな村は、偉大な魔法都市へと発展した。"},
{"id": 46, "en": "increase", "ja": "増える", "pronunciation": "ɪnˈkriːs", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "⬆️", "ex": "The number of stars increases every night.", "tr": "星の数は毎晩増えていく。"},
{"id": 47, "en": "reduce", "ja": "減らす", "pronunciation": "rɪˈduːs", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "⬇️", "ex": "The shield reduces the damage from the fire.", "tr": "盾は炎によるダメージを減らす。"},
{"id": 48, "en": "environment", "ja": "環境", "pronunciation": "ɪnˈvaɪrənmənt", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🌳", "ex": "The elves work hard to protect their forest environment.", "tr": "エルフたちは、森の環境を守るために懸命に働く。"},
{"id": 49, "en": "relationship", "ja": "関係", "pronunciation": "rɪˈleɪʃənʃɪp", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🔗", "ex": "The two kingdoms have a strong relationship.", "tr": "二つの王国は強い関係で結ばれている。"},
{"id": 50, "en": "opportunity", "ja": "機会", "pronunciation": "ˌɑːpərˈtuːnəti", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🚪", "ex": "A rare opportunity appeared before the young knight.", "tr": "若い騎士の前に、めったにない好機が現れた。"},
{"id": 51, "en": "responsibility", "ja": "責任", "pronunciation": "rɪˌspɑːnsəˈbɪləti", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🛡️", "ex": "A guardian carries a heavy responsibility.", "tr": "守護者は重い責任を背負っている。"},
{"id": 52, "en": "effective", "ja": "効果的な", "pronunciation": "ɪˈfektɪv", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🎯", "ex": "The potion was effective against the poison.", "tr": "その薬は毒に効果的だった。"},
{"id": 53, "en": "available", "ja": "利用できる", "pronunciation": "əˈveɪləbəl", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🟢", "ex": "Two rooms are available at the inn.", "tr": "宿には二部屋空いている。"},
{"id": 54, "en": "achieve", "ja": "達成する", "pronunciation": "əˈtʃiːv", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🏆", "ex": "She worked for years to achieve her dream.", "tr": "彼女は夢を達成するために何年も努力した。"},
{"id": 55, "en": "compare", "ja": "比べる", "pronunciation": "kəmˈper", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🔍", "ex": "The merchant compared the two swords carefully.", "tr": "商人は二本の剣を注意深く比べた。"},
{"id": 56, "en": "describe", "ja": "描写する", "pronunciation": "dɪˈskraɪb", "pos": "動詞", "rarity": "RARE", "stars": 3, "ic": "🖊️", "ex": "The traveler described the dragon to the villagers.", "tr": "旅人は村人たちにドラゴンの様子を語った。"},
{"id": 57, "en": "influence", "ja": "影響", "pronunciation": "ˈɪnfluəns", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🌊", "ex": "The moon has a strong influence on the tides.", "tr": "月は潮に強い影響を与える。"},
{"id": 58, "en": "purpose", "ja": "目的", "pronunciation": "ˈpɜːrpəs", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "🗺️", "ex": "What is the purpose of this ancient tower?", "tr": "この古い塔の目的は何だろう。"},
{"id": 59, "en": "popular", "ja": "人気のある", "pronunciation": "ˈpɑːpjələr", "pos": "形容詞", "rarity": "RARE", "stars": 3, "ic": "🌟", "ex": "The bard is popular in every town.", "tr": "その吟遊詩人はどの町でも人気だ。"},
{"id": 60, "en": "challenge", "ja": "挑戦", "pronunciation": "ˈtʃælɪndʒ", "pos": "名詞", "rarity": "RARE", "stars": 3, "ic": "⚔️", "ex": "The young hero accepted the challenge.", "tr": "若い勇者はその挑戦を受けた。"},
{"id": 61, "en": "implement", "ja": "実行する", "pronunciation": "ˈɪmplɪment", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "⚙️", "ex": "The council will implement the new plan tomorrow.", "tr": "評議会は明日、新しい計画を実行する。"},
{"id": 62, "en": "facilitate", "ja": "円滑にする", "pronunciation": "fəˈsɪlɪteɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🌉", "ex": "A magic bridge facilitates trade between the two kingdoms.", "tr": "魔法の橋が、二つの王国の交易を円滑にする。"},
{"id": 63, "en": "significant", "ja": "著しい", "pronunciation": "sɪɡˈnɪfɪkənt", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📊", "ex": "The wizard noticed a significant change in the stars.", "tr": "魔法使いは星に著しい変化を見つけた。"},
{"id": 64, "en": "potential", "ja": "可能性", "pronunciation": "pəˈtenʃəl", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🌰", "ex": "The boy has great potential as a mage.", "tr": "その少年には魔法使いとして大きな可能性がある。"},
{"id": 65, "en": "perspective", "ja": "視点", "pronunciation": "pərˈspektɪv", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🔭", "ex": "From the tower, she saw the city from a new perspective.", "tr": "塔の上から、彼女は町を新しい視点で見た。"},
{"id": 66, "en": "alternative", "ja": "代わりの", "pronunciation": "ɔːlˈtɜːrnətɪv", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "🛤️", "ex": "When the gate was sealed, they found an alternative route.", "tr": "門が封じられたとき、彼らは代わりの道を見つけた。"},
{"id": 67, "en": "consequence", "ja": "結果", "pronunciation": "ˈkɑːnsəkwens", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "💥", "ex": "The wizard faced the consequence of his forbidden spell.", "tr": "魔法使いは、禁断の呪文の報いに向き合った。"},
{"id": 68, "en": "accurate", "ja": "正確な", "pronunciation": "ˈækjərət", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📐", "ex": "The old map is accurate down to the last river.", "tr": "その古い地図は、小川ひとつまで正確だ。"},
{"id": 69, "en": "efficient", "ja": "効率的な", "pronunciation": "ɪˈfɪʃənt", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "⚡", "ex": "The dwarves built an efficient machine to mine the crystals.", "tr": "ドワーフたちは、水晶を掘るための効率的な機械を作った。"},
{"id": 70, "en": "strategy", "ja": "戦略", "pronunciation": "ˈstrætədʒi", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "♟️", "ex": "The queen studied the map and planned a bold strategy.", "tr": "女王は地図を調べ、大胆な戦略を立てた。"},
{"id": 71, "en": "evaluate", "ja": "評価する", "pronunciation": "ɪˈvæljueɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "📝", "ex": "The judges evaluate each mage's skill carefully.", "tr": "審査員は、それぞれの魔法使いの腕を慎重に評価する。"},
{"id": 72, "en": "analyze", "ja": "分析する", "pronunciation": "ˈænəlaɪz", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🔬", "ex": "The scholar analyzed the ancient runes for weeks.", "tr": "学者は何週間も古代のルーンを分析した。"},
{"id": 73, "en": "establish", "ja": "設立する", "pronunciation": "ɪˈstæblɪʃ", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🏛️", "ex": "The heroes established a guild in the northern city.", "tr": "勇者たちは北の町にギルドを設立した。"},
{"id": 74, "en": "maintain", "ja": "維持する", "pronunciation": "meɪnˈteɪn", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🔧", "ex": "The guards maintain the walls of the castle.", "tr": "衛兵たちは城壁を維持している。"},
{"id": 75, "en": "enhance", "ja": "高める", "pronunciation": "ɪnˈhæns", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "✨", "ex": "This gem can enhance the power of a spell.", "tr": "この宝石は呪文の力を高めることができる。"},
{"id": 76, "en": "criteria", "ja": "基準", "pronunciation": "kraɪˈtɪriə", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "📏", "ex": "The knight met all the criteria for the royal order.", "tr": "騎士は王の騎士団の基準をすべて満たした。"},
{"id": 77, "en": "priority", "ja": "優先事項", "pronunciation": "praɪˈɔːrəti", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🥇", "ex": "Protecting the villagers is our first priority.", "tr": "村人を守ることが、私たちの最優先事項だ。"},
{"id": 78, "en": "comprehensive", "ja": "包括的な", "pronunciation": "ˌkɑːmprɪˈhensɪv", "pos": "形容詞", "rarity": "EPIC", "stars": 4, "ic": "📚", "ex": "The library holds a comprehensive guide to magic.", "tr": "図書館には魔法の包括的な案内書がある。"},
{"id": 79, "en": "demonstrate", "ja": "実演する", "pronunciation": "ˈdemənstreɪt", "pos": "動詞", "rarity": "EPIC", "stars": 4, "ic": "🎤", "ex": "The master will demonstrate the spell to the students.", "tr": "師匠は生徒たちに呪文を実演してみせる。"},
{"id": 80, "en": "assumption", "ja": "前提", "pronunciation": "əˈsʌmpʃən", "pos": "名詞", "rarity": "EPIC", "stars": 4, "ic": "🎭", "ex": "Their plan was based on a false assumption.", "tr": "彼らの計画は誤った前提に基づいていた。"},
{"id": 81, "en": "leverage", "ja": "活用する", "pronunciation": "ˈlevərɪdʒ", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🏗️", "ex": "The merchant guild leveraged its alliances to expand into new markets.", "tr": "商人ギルドは、同盟関係を活用して新しい市場へ進出した。"},
{"id": 82, "en": "mitigate", "ja": "和らげる", "pronunciation": "ˈmɪtɪɡeɪt", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧯", "ex": "The archmage raised a barrier to mitigate the damage of the dragon's fire.", "tr": "大魔導師は、竜の炎の被害を和らげる結界を張った。"},
{"id": 83, "en": "acquisition", "ja": "買収", "pronunciation": "ˌækwɪˈzɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🏦", "ex": "The acquisition of the rival guild doubled the kingdom's trade.", "tr": "ライバルのギルドの買収が、王国の交易を倍にした。"},
{"id": 84, "en": "stakeholder", "ja": "利害関係者", "pronunciation": "ˈsteɪkhoʊldər", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧑‍🤝‍🧑", "ex": "Every stakeholder gathered at the round table to discuss the kingdom's future.", "tr": "すべての利害関係者が円卓に集まり、王国の未来を話し合った。"},
{"id": 85, "en": "compliance", "ja": "順守", "pronunciation": "kəmˈplaɪəns", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📜", "ex": "The guild ensured full compliance with the royal safety rules.", "tr": "ギルドは、王の安全規則への完全な順守を徹底した。"},
{"id": 86, "en": "revenue", "ja": "収益", "pronunciation": "ˈrevənuː", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "💰", "ex": "The harbor's revenue grew after the new ships arrived.", "tr": "新しい船が着いてから、港の収益は伸びた。"},
{"id": 87, "en": "disruption", "ja": "混乱", "pronunciation": "dɪsˈrʌpʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🌪️", "ex": "A sudden storm caused serious disruption to the trade routes.", "tr": "突然の嵐が、交易路に深刻な混乱を引き起こした。"},
{"id": 88, "en": "sustainable", "ja": "持続可能な", "pronunciation": "səˈsteɪnəbəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "♻️", "ex": "The elves designed a sustainable city that grows together with the forest.", "tr": "エルフたちは、森とともに育つ持続可能な都市を設計した。"},
{"id": 89, "en": "negotiation", "ja": "交渉", "pronunciation": "nɪˌɡoʊʃiˈeɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🕊️", "ex": "After a long negotiation, the two kingdoms signed a peace treaty.", "tr": "長い交渉の末、二つの王国は和平条約に署名した。"},
{"id": 90, "en": "collaboration", "ja": "協力", "pronunciation": "kəˌlæbəˈreɪʃən", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧩", "ex": "The collaboration of mages and smiths produced a legendary sword.", "tr": "魔法使いと鍛冶師の協力が、伝説の剣を生み出した。"},
{"id": 91, "en": "proactively", "ja": "先手を打って", "pronunciation": "ˌproʊˈæktɪvli", "pos": "副詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🚀", "ex": "The captain proactively reinforced the walls before the siege.", "tr": "隊長は包囲される前に、先手を打って城壁を補強した。"},
{"id": 92, "en": "substantial", "ja": "かなりの", "pronunciation": "səbˈstænʃəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🧱", "ex": "The dragon's hoard held a substantial amount of gold.", "tr": "竜の宝の山には、かなりの量の金貨があった。"},
{"id": 93, "en": "constraint", "ja": "制約", "pronunciation": "kənˈstreɪnt", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "⛓️", "ex": "The mages worked within strict constraints of time and mana.", "tr": "魔法使いたちは、時間と魔力の厳しい制約の中で働いた。"},
{"id": 94, "en": "incentive", "ja": "報奨", "pronunciation": "ɪnˈsentɪv", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🎁", "ex": "The king offered a golden incentive to anyone who could break the curse.", "tr": "王は、呪いを解いた者に金の報奨を約束した。"},
{"id": 95, "en": "scalable", "ja": "拡張可能な", "pronunciation": "ˈskeɪləbəl", "pos": "形容詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📶", "ex": "The guild built a scalable system that could grow with the city.", "tr": "ギルドは、街とともに拡大できる拡張可能な仕組みを作った。"},
{"id": 96, "en": "benchmark", "ja": "指標", "pronunciation": "ˈbentʃmɑːrk", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📍", "ex": "The old champion's record became the benchmark for every young knight.", "tr": "老いた王者の記録は、すべての若い騎士の目標となる指標になった。"},
{"id": 97, "en": "liability", "ja": "負債", "pronunciation": "ˌlaɪəˈbɪləti", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "💸", "ex": "An unpaid debt became a heavy liability for the merchant.", "tr": "未払いの借金は、商人にとって重い負債となった。"},
{"id": 98, "en": "contingency", "ja": "不測の事態", "pronunciation": "kənˈtɪndʒənsi", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🆘", "ex": "The general prepared a contingency plan in case the bridge fell.", "tr": "将軍は、橋が落ちた場合に備えて不測の事態への計画を用意した。"},
{"id": 99, "en": "deliverable", "ja": "成果物", "pronunciation": "dɪˈlɪvərəbəl", "pos": "名詞", "rarity": "LEGENDARY", "stars": 5, "ic": "📦", "ex": "Each apprentice submitted the final deliverable before the deadline.", "tr": "弟子たちはそれぞれ、期限前に成果物を提出した。"},
{"id": 100, "en": "streamline", "ja": "効率化する", "pronunciation": "ˈstriːmlaɪn", "pos": "動詞", "rarity": "LEGENDARY", "stars": 5, "ic": "🌀", "ex": "The guildmaster streamlined the process to save time.", "tr": "ギルド長は時間を節約するため、手順を効率化した。"}];
(function(){const s=new Set();WORDS.forEach(x=>{if(s.has(x.id))console.warn("単語のIDが重複しています:",x.id,x.en);s.add(x.id)});const m=Math.max(...s);if(m>=261)console.info("次に使うID: "+(m+1))})();
